name: Archive Source Repositories

on:
  issues:
    types: [opened, edited]

jobs:
  prepare:
    name: Prepare Repos Migration
    runs-on: Migration-fixed-ip-Ubuntu-4-core-runner
    container:
      image: ghcr.io/actions/actions-runner:latest
      options: --user root

    if: github.event_name == 'issues' &&
      (github.event.action == 'opened' || github.event.action == 'edited') &&
      contains(github.event.issue.labels.*.name, 'archive') &&
      !contains(github.event.issue.labels.*.name, 'gei-org')

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Parse issue body
        id: parse-issue-body
        uses: Legal-General-Group-Digital/github-issue-parser-action@v3

      - run: echo $JSON_STRING
        env:
          JSON_STRING: ${{ steps.parse-issue-body.outputs.jsonString }}

      - run: echo "$REPOSITORIES"
        env:
          REPOSITORIES: ${{ steps.parse-issue-body.outputs.issueparser_repositories }}

      - name: Post prepare message
        uses: actions/github-script@v6
        with:
          script: |
            
            let commentBody
            let repositories = process.env.REPOSITORIES.trim().split('\n');
      
            commentBody = `👋 Thank you for opening this migration issue.
            
            The following **${repositories.length} repositories** have been parsed from your issue body:

            \`\`\`
            ${repositories.join('\n')}
            \`\`\`

            <details>
              <summary><b>Troubleshooting</b></summary>

            If the parsed repositories are not matching the repositories listed in your issue body, you can edit the issue body and make sure it's correct. List your repositories in a code block as this one:

            \`\`\`
            your-org/your-repository-1
            your-org/your-repository-2
            \`\`\`
            </details>

            ## Run the migration

            Open a new issue by choosing the appropriate issue template on the same repository
            `
            await github.rest.issues.createComment({
                issue_number: ${{ github.event.issue.number }},
                owner: '${{ github.REPOSITORY_OWNER }}',
                repo: '${{ github.event.repository.name }}',
                body: commentBody
            })
        env:
          REPOSITORIES: ${{ steps.parse-issue-body.outputs.issueparser_repositories }}

      - name: Post failure message
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            let commentBody
            commentBody = `😢 The issue body could not be parsed. Please edit the issue body or open a new issue using an issue template.`
            await github.rest.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: '${{ github.REPOSITORY_OWNER }}',
              repo: '${{ github.event.repository.name }}',
              body: commentBody
            })
      
      - name: Archive repositories
        id: archive-repos
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.SOURCE_ADMIN_TOKEN }}
          script: |
            const fs = require('fs');
            const repositories = process.env.REPOSITORIES.split('\n');
            const labels = process.env.LABELS;
            let isfailed = false;
            let report = '';

            // Function to introduce delay
            const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

            for (const sourceRepo of repositories) {
              if (sourceRepo) {
                let [sourceOrg, repoName] = sourceRepo.split('/');
                repoName = repoName.trim();

                core.info(`Archiving ${sourceOrg}/${repoName}`);
                try {
                  const response = await github.rest.repos.update({
                    owner: sourceOrg,
                    repo: repoName,
                    archived: true
                  });
                  if (response.status === 200) {
                    report += `${repoName} archival successful\n`;
                  } else {
                    report += `${repoName} archival unsuccessful\n`;
                    isfailed = true;
                  }
                } catch (error) {
                  report += `${repoName} archival unsuccessful\n`;
                  core.error(`Failed to archive ${sourceOrg}/${repoName}: ${error.message}`);
                  isfailed = true;
                }

                // Delay for 2 seconds between requests to avoid rate limiting
                await delay(2000);
              }
            }
            fs.writeFileSync('report_archival.txt', report);
            if (isfailed) {
              core.setFailed('Failed to archive one or more repositories');
            }
        env:
          REPOSITORIES: ${{ steps.parse-issue-body.outputs.issueparser_repositories }}
          LABELS: ${{ toJSON(github.event.issue.labels.*.name) }}

      - name: Upload Archival report
        if: always() && steps.archive-repos.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report_archival.txt

      - name: Update issue with failed archival
        if: always() && steps.archive-repos.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const body = `Failed to **Archive** repositories post migration. [View workflow run for details](${context.payload.repository.html_url}/actions/runs/${context.runId})\n\n`
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })

      - name: Update issue with running state
        uses: actions/github-script@v7
        with:
          script: |
            const body = `:wastebasket: **Archived** repositories post migration. [View workflow run for details](${context.payload.repository.html_url}/actions/runs/${context.runId})\n\n`
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })
