name: Repository Migration for Big Repos[GEI]

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write

jobs:
  migrate:
    if: contains(github.event.issue.labels.*.name, 'big-migration') &&
        contains(github.event.issue.labels.*.name, 'gei') &&
        !startsWith(github.event.comment.body, '/delete-repositories')
    uses: ./.github/workflows/041.repository.migration-BIG.execution.yml
    secrets: inherit
      # TARGET_ADMIN_TOKEN: ${{ secrets.TARGET_ADMIN_TOKEN }}
      # SOURCE_ADMIN_TOKEN: ${{ secrets.SOURCE_ADMIN_TOKEN }}
      # GK_PAT: ${{ secrets.GH_MIGRATION_PAT }}
